#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Error - ingrese directorio como argumento"
	echo "Syntax : $0 directorio"
	echo "Uso: borrar directorios"
	exit 1
fi
for i in $@; do
	if [ -e $i ]; then
		rm -r $i
	else
		echo "::: El directorio $i no existe :::"
	fi
done


