#!/bin/bash

function crearDir(){
	while true
	do
		echo -n "Ingrese nombre de directorio a crear: "
		read nuevodirectorio
		if [ -d $nuevodirectorio ]; then 
				echo "::: El directorio ya existe :::"
		else 
			mkdir $nuevodirectorio
			if [ $? -eq 0 ]; then
				echo "- El directorio $nuevodirectorio fue creado con exito"
				#ls -la . | grep $nuevodirectorio
				return
			fi
			
		fi
	done
}

function volver() {
	echo -e "--------------------------------------------"
	echo "::: Presione Enter para volver al menu :::"
	echo -e "--------------------------------------------"
	read
}

while true
do
	clear
	echo -e "--------------------------------------------"
	echo -e "MENU PRINCIPAL  \t"
	echo -e "\t  1. Contar archivos de un directorio  "
	echo -e "\t  2. Listar directorio de trabajo  "
	echo -e "\t  3. Crear directorio nuevo  "
	echo -e "\t  4. Borrar directorios  "
	echo -e "\t  5. Salir  "
	echo -e "--------------------------------------------"
	read -p "Ingrese la opcion: " opcion
	echo -e "--------------------------------------------"
	case $opcion in
		1)./contarArchivos;volver;;
		2)echo -n `pwd`;echo ": ";ls .;volver;;
		3)crearDir;volver;;
		4)echo -n "Ingrese el directorio a borrar: "; read borrarD; ./borrarDir $borrarD;volver;;
		5)exit 0;;
		*)echo "::: Error: opcion incorrecta :::";;
	esac
done
